name: fenicsxconcrete
channels:
  - conda-forge
dependencies:
  # runtime
  - fenics-dolfinx
  - pint
  - loguru
  - matplotlib
  # tests
  - pytest
  - coverage
  - toml
  - pip
  - pip:
      - -e .
