name: fenicsxconcrete1
channels:
  - conda-forge
dependencies:
  - python>=3.10
  # runtime
  - fenics-dolfinx=0.6.0
  - mpi4py=3.1.4
  - scipy
  - pint
  - matplotlib
  - python-gmsh=4.11.1
  - meshio=5.3.4
  - jsonschema
  - numba
  # tests
  - pytest
  - coverage
  - toml
  # docs
  - sphinx
  - sphinx-gallery
  - myst-parser
  - sphinx_rtd_theme
  # environment
  - conda-ecosystem-user-package-isolation
  # formatting
  - black
  - isort
  - pip
  - pip:
    - git+https://github.com/BAMresearch/fenics-constitutive.git@4abacc145638129eb8b6cc87325dd0d43a65fdd6
    - -e .

