{% set name = "FenicsXConcrete" %}
{% set pyproject = load_file_data('../pyproject.toml', from_recipe_dir=true) %}
{% set version = pyproject.get('version') %}
# For setting the version, set the desired value in pyproject.toml
# This should also work for pre-releases like 0.0.1-alpha
# Next, create/draft a new release with a tag equal to version (prefixed with v)
# and choose the correct branch as target.
# Example: version = "0.0.5-alpha" in pyproject.toml
# tag --> v0.0.5-alpha

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/BAMresearch/FenicsXConcrete/archive/refs/tags/v{{ version }}.tar.gz

build:
  skip: True  # [win or osx]
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv
  number: 0

requirements:
  host:
    - python
    - pip
    - setuptools

  run:
    - fenics-dolfinx
    - matplotlib
    - meshio
    - pint
    - python
    - python-gmsh

test:
  imports:
    - fenicsxconcrete

  source_files:
    - tests

  requires:
    - pytest

  commands:
    - pytest tests

about:
  home: https://github.com/BAMresearch/FenicsXConcrete
  license: MIT
  license_family: MIT
  summary: Computation for concrete structures using FEniCSX
