{% set name = "FenicsXConcrete" %}
# For setting the version, either tag your git commit,
# or set an environment variable GIT_DESCRIBE_TAG

package:
  name: {{ name|lower }}
  version: 0.0.1
  # version: {{ environ.get('GIT_DESCRIBE_TAG', '') }}

source:
  git_url: https://github.com/BAMresearch/FenicsXConcrete
  git_tag: 26-update-github-actions-to-build-conda-package
  # git_rev: {{ environ.get('GIT_DESCRIBE_TAG', '') }}

build:
  skip: True  # [win or osx]
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv
  number: 0

requirements:
  host:
    - python
    - pip
    - setuptools

  run:
    - python
    - pint
    - fenics-dolfinx

test:
  imports:
    - fenicsxconcrete

  source_files:
    - tests

  requires:
    - pytest

  commands:
    - pytest tests

about:
  home: https://github.com/BAMresearch/FenicsXConcrete
  license: MIT
  license_family: MIT
  summary: Computation for concrete structures using FEniCSX
