{% set name = "FenicsXConcrete" %}
{% set pyproject = load_file_data('../pyproject.toml', from_recipe_dir=true) %}
# Use pyproject as single source for version variable

package:
  name: {{ name|lower }}
  version: {{ pyproject.get('version') }}

source:
  git_url: https://github.com/BAMresearch/FenicsXConcrete
  git_tag: 26-update-github-actions-to-build-conda-package

build:
  skip: True  # [win or osx]
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv
  number: 0

requirements:
  host:
    - python
    - pip
    - setuptools

  run:
    - python
    - pint
    - fenics-dolfinx

test:
  imports:
    - fenicsxconcrete

  source_files:
    - tests

  requires:
    - pytest

  commands:
    - pytest tests

about:
  home: https://github.com/BAMresearch/FenicsXConcrete
  license: MIT
  license_family: MIT
  summary: Computation for concrete structures using FEniCSX
