name: coverage check
on:
  push:
    branches-ignore:

  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:


jobs:
  coverage_check:
    runs-on: ubuntu-latest
    permissions: {}
    steps:
      - name: print branch name
        run: |
          BRANCH_NAME=$(echo ${GITHUB_REF#refs/heads/} | sed "s/\//_/g")
          echo $BRANCH_NAME  
          echo "$BRANCH_NAME" 
          echo "$GITHUB_REF"


      - name: show content
        run: |
          echo "https://gist.githubusercontent.com/eriktamsen/c10a5b6d0714b1fe2344eb60918e92f8/raw/9c770f9f225652400e55147cef82b3d1247c8545/fenicsxconcrete_main_coverage.json"
          echo $.getJSON("https://gist.githubusercontent.com/eriktamsen/c10a5b6d0714b1fe2344eb60918e92f8/raw/9c770f9f225652400e55147cef82b3d1247c8545/fenicsxconcrete_main_coverage.json")  # , function(data){console.log(data);}