name: coverage check
on:
  push:
    branches-ignore:

  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:


jobs:
  coverage_check:
    runs-on: ubuntu-latest
    permissions: {}
    steps:
      - name: print stuff
        run: |
          BRANCH_NAME=$(echo ${GITHUB_REF#refs/heads/})
          BRANCH_NAME=$(echo $env.BRANCH_NAME | sed "s/\//_/g")"
          echo "fenicsxconcrete_${{ env.BRANCH_NAME }}_coverage.json"
          echo "$GITHUB_REF"
