name: coverage check
on:
  push:
    branches-ignore:

  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:


jobs:
  coverage_check:
    runs-on: ubuntu-latest
    permissions: {}
    steps:
      - name: print branch name and coverage
        run: |
          BRANCH_NAME=$(echo ${GITHUB_REF#refs/heads/} | sed "s/\//_/g")
          curl -X GET "https://gist.githubusercontent.com/eriktamsen/c10a5b6d0714b1fe2344eb60918e92f8/raw/fenicsxconcrete_{$BRANCH_NAME}_coverage.json"

      - name: show content
        run: |
          CODE=$(curl -X GET "https://gist.githubusercontent.com/eriktamsen/c10a5b6d0714b1fe2344eb60918e92f8/raw/fenicsxconcrete_main_coverage.json")
          echo '------------------------'
          echo $CODE
          echo '------------------------'
          NEWCODE=$(echo $CODE | | grep -oP "\d+%")
          echo $NEWCODE
          