name: coverage check
on:
  push:
    branches-ignore:

  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:


jobs:
  use_api:
    runs-on: ubuntu-latest
    permissions: {}
    steps:
      - env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh api --header 'Accept: application/vnd.github+json' \
                 --method POST /repos/octocat/Spoon-Knife/issues \
                 -f title="Created with the REST API" \
                 -f body="This is a test issue created by the REST API"
