name: coverage check

# Only trigger, when the test workflow succeeded
on:
  workflow_run:
    workflows: ["push"]
    types:
      - completed

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:


jobs:
  coverage_check:
    runs-on: ubuntu-latest
    permissions: {}
    steps:
      - name: check coverage
        run: |
          BRANCH_NAME=$(echo ${GITHUB_REF#refs/heads/} | sed "s/\//_/g")
          BRANCH_DATA=$(curl -s -X GET "https://gist.githubusercontent.com/eriktamsen/c10a5b6d0714b1fe2344eb60918e92f8/raw/fenicsxconcrete_{$BRANCH_NAME}_coverage.json")
          BRANCH_COVERAGE=$(echo $BRANCH_DATA | grep -o -P 'message.{3,6}' | sed -e 's/"//g' | sed -e 's/://g' | sed -e 's/message//g' | sed -e 's/%//g' | sed -e 's/,//g')
          echo "Coverage of current branch: $BRANCH_COVERAGE"
          declare -i int_branch_coverage=$BRANCH_COVERAGE
          MAIN_DATA=$(curl -s -X GET "https://gist.githubusercontent.com/eriktamsen/c10a5b6d0714b1fe2344eb60918e92f8/raw/fenicsxconcrete_main_coverage.json")
          MAIN_COVERAGE=$(echo $MAIN_DATA | grep -o -P 'message.{3,6}' | sed -e 's/"//g' | sed -e 's/://g' | sed -e 's/message//g' | sed -e 's/%//g' | sed -e 's/,//g')
          echo "Coverage of main branch: $MAIN_COVERAGE"
          declare -i int_main_coverage=$MAIN_COVERAGE
          delta_coverage=$(( int_branch_coverage - int_main_coverage  ))
          echo "Increase in coverage: $delta_coverage"
          if [[ $delta_coverage -lt 0 ]]
          then
            echo "The current branch has lower coverage than the main branch, please improve your code"
            exit 1
          fi
          echo "Passing!!!"
          


