name: publish_conda

on:
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          channels: conda-forge,defaults
          channel-priority: true

      - name: Build and upload
        shell: bash -l {0}
        env:
          ANACONDA_TOKEN: ${{ secrets.ANACONDA_TOKEN }}
        run: |
          conda install conda-build anaconda-client conda-verify
          conda config --set anaconda_upload yes
          cd $GITHUB_WORKSPACE
          conda build --token "$ANACONDA_TOKEN" --user bam77 .conda -m .conda/conda_build_config.yaml
