name: output
on:
  push:
    branches-ignore:

  pull_request:
    branches: [ main ]

env:
  CACHE_NUMBER: 1 # increase to reset cache manually

jobs:
  tests:
    runs-on: ubuntu-latest

    outputs:
      branch_coverage: ${{ steps.pytest.outputs.coverage }}

    steps:
      - name: pytest
        id: pytest
        shell: bash -l {0}
        run: |
          echo "coverage=$(echo "Moin")" >> $GITHUB_OUTPUT  # to be used in next job

  check_coverage:
    needs: tests
    runs-on: ubuntu-latest
    steps:
      - name: check coverage
        run: |
          echo "Here is the current coverage report:"
          echo "${{ needs.tests.outputs.branch_coverage }}"
  
